name: Selenium Tests

on:
  push:
    branches:
      - main  # Modify the branch name if necessary

jobs:
  selenium_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Install Selenium IDE
      run: npm install -g selenium-side-runner

    - name: Run Selenium Tests
      run: |
        selenium-side-runner selenium_swati_assign.side
